// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_rtestim_RCPPEXPORTS_H_GEN_
#define RCPP_rtestim_RCPPEXPORTS_H_GEN_

#include <RcppEigen.h>
#include <Rcpp.h>

namespace rtestim {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("rtestim", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("rtestim", "_rtestim_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in rtestim");
            }
        }
    }

    inline NumericVector rcpp_tvdz(NumericVector y, NumericVector z, double lambda) {
        typedef SEXP(*Ptr_rcpp_tvdz)(SEXP,SEXP,SEXP);
        static Ptr_rcpp_tvdz p_rcpp_tvdz = NULL;
        if (p_rcpp_tvdz == NULL) {
            validateSignature("NumericVector(*rcpp_tvdz)(NumericVector,NumericVector,double)");
            p_rcpp_tvdz = (Ptr_rcpp_tvdz)R_GetCCallable("rtestim", "_rtestim_rcpp_tvdz");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_rcpp_tvdz(Shield<SEXP>(Rcpp::wrap(y)), Shield<SEXP>(Rcpp::wrap(z)), Shield<SEXP>(Rcpp::wrap(lambda)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<NumericVector >(rcpp_result_gen);
    }

    inline NumericVector rcpp_wtvdz(NumericVector y, NumericVector z, double lambda, NumericVector weights) {
        typedef SEXP(*Ptr_rcpp_wtvdz)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_rcpp_wtvdz p_rcpp_wtvdz = NULL;
        if (p_rcpp_wtvdz == NULL) {
            validateSignature("NumericVector(*rcpp_wtvdz)(NumericVector,NumericVector,double,NumericVector)");
            p_rcpp_wtvdz = (Ptr_rcpp_wtvdz)R_GetCCallable("rtestim", "_rtestim_rcpp_wtvdz");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_rcpp_wtvdz(Shield<SEXP>(Rcpp::wrap(y)), Shield<SEXP>(Rcpp::wrap(z)), Shield<SEXP>(Rcpp::wrap(lambda)), Shield<SEXP>(Rcpp::wrap(weights)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<NumericVector >(rcpp_result_gen);
    }

}

#endif // RCPP_rtestim_RCPPEXPORTS_H_GEN_
