// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// admm_eigen_testing
List admm_eigen_testing(int M, NumericVector const& y, NumericVector const& x, NumericVector const& w, int n, int ord, NumericVector theta, NumericVector z, NumericVector u, double lambda, double rho, double mu, double tol, int iter);
RcppExport SEXP _rtestim_admm_eigen_testing(SEXP MSEXP, SEXP ySEXP, SEXP xSEXP, SEXP wSEXP, SEXP nSEXP, SEXP ordSEXP, SEXP thetaSEXP, SEXP zSEXP, SEXP uSEXP, SEXP lambdaSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP tolSEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< NumericVector const& >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector const& >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type ord(ordSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    rcpp_result_gen = Rcpp::wrap(admm_eigen_testing(M, y, x, w, n, ord, theta, z, u, lambda, rho, mu, tol, iter));
    return rcpp_result_gen;
END_RCPP
}
// dptfe
Rcpp::NumericVector dptfe(Rcpp::NumericVector y, double lam);
RcppExport SEXP _rtestim_dptfe(SEXP ySEXP, SEXP lamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    rcpp_result_gen = Rcpp::wrap(dptfe(y, lam));
    return rcpp_result_gen;
END_RCPP
}
// dptfe_past
Rcpp::NumericVector dptfe_past(Rcpp::NumericVector y, double lam, Rcpp::NumericVector w);
RcppExport SEXP _rtestim_dptfe_past(SEXP ySEXP, SEXP lamSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(dptfe_past(y, lam, w));
    return rcpp_result_gen;
END_RCPP
}
// get_Dtil
Eigen::SparseMatrix<double> get_Dtil(int k, NumericVector xd);
RcppExport SEXP _rtestim_get_Dtil(SEXP kSEXP, SEXP xdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xd(xdSEXP);
    rcpp_result_gen = Rcpp::wrap(get_Dtil(k, xd));
    return rcpp_result_gen;
END_RCPP
}
// get_D
Eigen::SparseMatrix<double> get_D(int k, NumericVector xd);
RcppExport SEXP _rtestim_get_D(SEXP kSEXP, SEXP xdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xd(xdSEXP);
    rcpp_result_gen = Rcpp::wrap(get_D(k, xd));
    return rcpp_result_gen;
END_RCPP
}
// doDv
NumericVector doDv(NumericVector v, int k, NumericVector xd);
RcppExport SEXP _rtestim_doDv(SEXP vSEXP, SEXP kSEXP, SEXP xdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xd(xdSEXP);
    rcpp_result_gen = Rcpp::wrap(doDv(v, k, xd));
    return rcpp_result_gen;
END_RCPP
}
// doDtv
NumericVector doDtv(NumericVector v, int k, NumericVector xd);
RcppExport SEXP _rtestim_doDtv(SEXP vSEXP, SEXP kSEXP, SEXP xdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xd(xdSEXP);
    rcpp_result_gen = Rcpp::wrap(doDtv(v, k, xd));
    return rcpp_result_gen;
END_RCPP
}
// doDtDv
NumericVector doDtDv(NumericVector v, int k, NumericVector xd);
RcppExport SEXP _rtestim_doDtDv(SEXP vSEXP, SEXP kSEXP, SEXP xdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xd(xdSEXP);
    rcpp_result_gen = Rcpp::wrap(doDtDv(v, k, xd));
    return rcpp_result_gen;
END_RCPP
}
// buildD
arma::sp_mat buildD(int n, int ord);
RcppExport SEXP _rtestim_buildD(SEXP nSEXP, SEXP ordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type ord(ordSEXP);
    rcpp_result_gen = Rcpp::wrap(buildD(n, ord));
    return rcpp_result_gen;
END_RCPP
}
// buildDx
arma::sp_mat buildDx(int n, int ord, const arma::vec& x);
RcppExport SEXP _rtestim_buildDx(SEXP nSEXP, SEXP ordSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type ord(ordSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(buildDx(n, ord, x));
    return rcpp_result_gen;
END_RCPP
}
// buildDx_tilde
arma::sp_mat buildDx_tilde(int n, int ord, const arma::vec& x);
RcppExport SEXP _rtestim_buildDx_tilde(SEXP nSEXP, SEXP ordSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type ord(ordSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(buildDx_tilde(n, ord, x));
    return rcpp_result_gen;
END_RCPP
}
// create_lambda_test
arma::vec create_lambda_test(arma::vec lambda, double lambdamin, double lambdamax, double lambda_min_ratio, int nsol);
RcppExport SEXP _rtestim_create_lambda_test(SEXP lambdaSEXP, SEXP lambdaminSEXP, SEXP lambdamaxSEXP, SEXP lambda_min_ratioSEXP, SEXP nsolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambdamin(lambdaminSEXP);
    Rcpp::traits::input_parameter< double >::type lambdamax(lambdamaxSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_min_ratio(lambda_min_ratioSEXP);
    Rcpp::traits::input_parameter< int >::type nsol(nsolSEXP);
    rcpp_result_gen = Rcpp::wrap(create_lambda_test(lambda, lambdamin, lambdamax, lambda_min_ratio, nsol));
    return rcpp_result_gen;
END_RCPP
}
// gaussianized_data
arma::vec gaussianized_data(arma::vec const& y, arma::vec const& w, arma::vec& theta);
RcppExport SEXP _rtestim_gaussianized_data(SEXP ySEXP, SEXP wSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec const& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussianized_data(y, w, theta));
    return rcpp_result_gen;
END_RCPP
}
// line_search
double line_search(double s, double lambda, double alpha, double gamma, arma::vec const& y, arma::vec const& x, arma::vec const& w, int n, int ord, arma::vec& theta, arma::vec& theta_old, arma::vec& c1, arma::vec& c2, int M);
RcppExport SEXP _rtestim_line_search(SEXP sSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP gammaSEXP, SEXP ySEXP, SEXP xSEXP, SEXP wSEXP, SEXP nSEXP, SEXP ordSEXP, SEXP thetaSEXP, SEXP theta_oldSEXP, SEXP c1SEXP, SEXP c2SEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type ord(ordSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type theta_old(theta_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type c2(c2SEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(line_search(s, lambda, alpha, gamma, y, x, w, n, ord, theta, theta_old, c1, c2, M));
    return rcpp_result_gen;
END_RCPP
}
// calcDvline_test
arma::vec calcDvline_test(int n, int ord, arma::vec const& x, arma::vec& v, arma::vec& b);
RcppExport SEXP _rtestim_calcDvline_test(SEXP nSEXP, SEXP ordSEXP, SEXP xSEXP, SEXP vSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type ord(ordSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(calcDvline_test(n, ord, x, v, b));
    return rcpp_result_gen;
END_RCPP
}
// calcDTvline_test
arma::vec calcDTvline_test(int n, int ord, arma::vec const& x, arma::vec& v, arma::vec& b);
RcppExport SEXP _rtestim_calcDTvline_test(SEXP nSEXP, SEXP ordSEXP, SEXP xSEXP, SEXP vSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type ord(ordSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(calcDTvline_test(n, ord, x, v, b));
    return rcpp_result_gen;
END_RCPP
}
// calcDTDvline_test
arma::vec calcDTDvline_test(int n, int ord, arma::vec const& x, arma::vec& v, arma::vec& b);
RcppExport SEXP _rtestim_calcDTDvline_test(SEXP nSEXP, SEXP ordSEXP, SEXP xSEXP, SEXP vSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type ord(ordSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(calcDTDvline_test(n, ord, x, v, b));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_rtestim_admm_eigen_testing", (DL_FUNC) &_rtestim_admm_eigen_testing, 14},
    {"_rtestim_dptfe", (DL_FUNC) &_rtestim_dptfe, 2},
    {"_rtestim_dptfe_past", (DL_FUNC) &_rtestim_dptfe_past, 3},
    {"_rtestim_get_Dtil", (DL_FUNC) &_rtestim_get_Dtil, 2},
    {"_rtestim_get_D", (DL_FUNC) &_rtestim_get_D, 2},
    {"_rtestim_doDv", (DL_FUNC) &_rtestim_doDv, 3},
    {"_rtestim_doDtv", (DL_FUNC) &_rtestim_doDtv, 3},
    {"_rtestim_doDtDv", (DL_FUNC) &_rtestim_doDtDv, 3},
    {"_rtestim_buildD", (DL_FUNC) &_rtestim_buildD, 2},
    {"_rtestim_buildDx", (DL_FUNC) &_rtestim_buildDx, 3},
    {"_rtestim_buildDx_tilde", (DL_FUNC) &_rtestim_buildDx_tilde, 3},
    {"_rtestim_create_lambda_test", (DL_FUNC) &_rtestim_create_lambda_test, 5},
    {"_rtestim_gaussianized_data", (DL_FUNC) &_rtestim_gaussianized_data, 3},
    {"_rtestim_line_search", (DL_FUNC) &_rtestim_line_search, 14},
    {"_rtestim_calcDvline_test", (DL_FUNC) &_rtestim_calcDvline_test, 5},
    {"_rtestim_calcDTvline_test", (DL_FUNC) &_rtestim_calcDTvline_test, 5},
    {"_rtestim_calcDTDvline_test", (DL_FUNC) &_rtestim_calcDTDvline_test, 5},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rtestim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
