# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prox_dp_norm <- function(y, lam) {
    .Call('_rtestim_prox_dp_norm', PACKAGE = 'rtestim', y, lam)
}

admm <- function(M, y, x, n, theta, z, u, lambda, rho, mu, D, tol = 1e-3) {
    .Call('_rtestim_admm', PACKAGE = 'rtestim', M, y, x, n, theta, z, u, lambda, rho, mu, D, tol)
}

