# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linear_admm_testing <- function(M, y, x, w, n, ord, theta, z, u, lambda, rho, mu, tol, iter) {
    .Call(`_rtestim_linear_admm_testing`, M, y, x, w, n, ord, theta, z, u, lambda, rho, mu, tol, iter)
}

admm_gauss <- function(M, n, ord, y, x, w, theta, z, u, rho, lam_z, r_norm, s_norm, DD, tol) {
    .Call(`_rtestim_admm_gauss`, M, n, ord, y, x, w, theta, z, u, rho, lam_z, r_norm, s_norm, DD, tol)
}

prox_newton_testing <- function(M, M_inner, n, ord, y, x, w, theta, z, u, lambda, rho, alpha, gamma, D, tol, iter) {
    .Call(`_rtestim_prox_newton_testing`, M, M_inner, n, ord, y, x, w, theta, z, u, lambda, rho, alpha, gamma, D, tol, iter)
}

dptf <- function(y, lam) {
    .Call(`_rtestim_dptf`, y, lam)
}

dptf_past <- function(y, lam, w) {
    .Call(`_rtestim_dptf_past`, y, lam, w)
}

rtestim_path <- function(algo, y, x, w, korder, lambda, lambdamax = -1, lambdamin = -1, nsol = 100L, rho = -1, maxiter = 1e5L, maxiter_inner = 5L, tolerance = 1e-3, lambda_min_ratio = 1e-4, ls_alpha = 0.5, ls_gamma = 0.9, verbose = 0L) {
    .Call(`_rtestim_rtestim_path`, algo, y, x, w, korder, lambda, lambdamax, lambdamin, nsol, rho, maxiter, maxiter_inner, tolerance, lambda_min_ratio, ls_alpha, ls_gamma, verbose)
}

get_Dtil <- function(k, xd) {
    .Call(`_rtestim_get_Dtil`, k, xd)
}

get_D <- function(k, xd) {
    .Call(`_rtestim_get_D`, k, xd)
}

buildD <- function(n, ord) {
    .Call(`_rtestim_buildD`, n, ord)
}

buildDx <- function(n, ord, x) {
    .Call(`_rtestim_buildDx`, n, ord, x)
}

buildDx_tilde <- function(n, ord, x) {
    .Call(`_rtestim_buildDx_tilde`, n, ord, x)
}

create_lambda_test <- function(lambda, lambdamin, lambdamax, lambda_min_ratio, nsol) {
    .Call(`_rtestim_create_lambda_test`, lambda, lambdamin, lambdamax, lambda_min_ratio, nsol)
}

gaussianized_data <- function(y, w, theta) {
    .Call(`_rtestim_gaussianized_data`, y, w, theta)
}

line_search <- function(s, lambda, alpha, gamma, y, x, w, n, ord, theta, theta_old, c1, c2, M) {
    .Call(`_rtestim_line_search`, s, lambda, alpha, gamma, y, x, w, n, ord, theta, theta_old, c1, c2, M)
}

calcDvline_test <- function(n, ord, x, v, b) {
    .Call(`_rtestim_calcDvline_test`, n, ord, x, v, b)
}

calcDTvline_test <- function(n, ord, x, v, b) {
    .Call(`_rtestim_calcDTvline_test`, n, ord, x, v, b)
}

calcDTDvline_test <- function(n, ord, x, v, b) {
    .Call(`_rtestim_calcDTDvline_test`, n, ord, x, v, b)
}

